// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk9JfgfVnWf28PfeKHZL8cI41x6VCFZJU',
    appId: '1:608591321767:web:74a0f9b2f8c59ef5849982',
    messagingSenderId: '608591321767',
    projectId: 'chatter-app-7-f',
    authDomain: 'chatter-app-7-f.firebaseapp.com',
    storageBucket: 'chatter-app-7-f.firebasestorage.app',
    measurementId: 'G-E57N1GNKZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaMpPzgeGN9WZy_ojmqrdmlivC0MLF3bA',
    appId: '1:608591321767:android:347ace31a40d52e1849982',
    messagingSenderId: '608591321767',
    projectId: 'chatter-app-7-f',
    storageBucket: 'chatter-app-7-f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIrNPmctGMK7gtdg70ac0nJcOXQqUlwjs',
    appId: '1:608591321767:ios:5e7e05f3ad219d9a849982',
    messagingSenderId: '608591321767',
    projectId: 'chatter-app-7-f',
    storageBucket: 'chatter-app-7-f.firebasestorage.app',
    iosBundleId: 'com.learners.chatterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIrNPmctGMK7gtdg70ac0nJcOXQqUlwjs',
    appId: '1:608591321767:ios:5e7e05f3ad219d9a849982',
    messagingSenderId: '608591321767',
    projectId: 'chatter-app-7-f',
    storageBucket: 'chatter-app-7-f.firebasestorage.app',
    iosBundleId: 'com.learners.chatterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk9JfgfVnWf28PfeKHZL8cI41x6VCFZJU',
    appId: '1:608591321767:web:ae71892de496e3b7849982',
    messagingSenderId: '608591321767',
    projectId: 'chatter-app-7-f',
    authDomain: 'chatter-app-7-f.firebaseapp.com',
    storageBucket: 'chatter-app-7-f.firebasestorage.app',
    measurementId: 'G-FDVSR19PS4',
  );
}
